services:
  - type: web
    runtime: python
    name: jenkins-chatbot
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHONPATH
        value: /app